fix: changing a hostgroup's organization crashes when plugin installed
Before this commit, changing a hostgroup's organization or location
crashed with the following error:
"undefined method `updated?' for #<ActiveRecord::Associations::[...]"

This was caused by the Ansible lifecycle environment association
sharing the name as the Katello lifecycle environment association.

Both associations were called "lifeycle_environment", which caused
ActiveRecord to incorrectly attempt to update the hostgroup object.

This is fixed by renaming the association stemming from this plugin
to "ansible_lifecycle_environment", which is unique.
No database changes have to be made, as the respective foreign key
is already named "ansible_lifecycle_environment_id".